fix
snphq/react-sortable-hoc pull request #2
Opened 2017-09-04 15:13 UTC by mixa9269

fix simultaneous drag nested elements;
add selectedClass;
add zIndex for helper;
fix GetScrollContainer();
add prevItem to multipleSortEnd info;
fix multiple drag;

2017-09-05 11:00 UTC, AleksandrLv requested changes

2017-09-05 11:00 UTC, AleksandrLv commented on src/.stories/NestedListsWithMultipleDrag.js
> +            distance={3}/>
/> на новой строчке должно быть

2017-09-05 11:00 UTC, AleksandrLv commented on src/DragLayer/index.js
> +    this.selectedItems.forEach(item=>item.unselect());
unselectAll() { - пробел забыл. Везде в таких местах поправь
this.selectedItems.forEach(item => item.unselect()); - тоже пробелы

2017-09-05 11:00 UTC, AleksandrLv commented on src/DragLayer/index.js
> +    this.lists.forEach(list => list.manager.selected=[]);
list.manager.selected = []);
У тебя линтер стоит какой-нибудь?

2017-09-05 11:00 UTC, AleksandrLv commented on src/DragLayer/index.js
>        }else{
if (pageY > this.oldY) {
} else {
В подобных местах поправь

2017-09-05 11:00 UTC, AleksandrLv commented on src/SortableContainer/index.js
> +var isDrag = false;
var? наверно, опечатка
И почему сюда вынес, а не в конструкторе объявил?

2017-09-05 11:00 UTC, AleksandrLv commented on src/SortableContainer/index.js
> +          for (let i=0;i<list.props.items.length;i++){
for (let i = 0; i < list.props.items.length; i++) {
Во всех своих файлах посмотри на правильность расстановки пробелов и поправь

2017-09-05 11:00 UTC, AleksandrLv commented on src/SortableContainer/index.js
> +      const index = this.index = activeNode.node.sortableInfo.index;
Разве это все не излишне?
this.index = activeNode.node.sortableInfo.index; Так не подойдёт?

2017-09-05 11:00 UTC, AleksandrLv commented on src/SortableElement/index.js
> +        </div>;
Читается не очень.
Лучше так
```
return (
    <div>
        onClick={}
    </div>
);

2017-09-05 11:00 UTC, AleksandrLv commented on src/SortableElement/index.js
> +      />;
Лучше так записать
```
const component = (
    <WrappedComponent
        ref={ref}
        {...props}
    />
);

2017-09-05 11:00 UTC, AleksandrLv commented on src/SortableElement/index.js
> +          </div>
Сразу не понял что к чему, т.к. запись не очень удачна.
```
<div>
    {selectedItems.map((value, index) =>
        <div
            key={index}
            className={this.helperClass}
        >
            <WrappedComponent
                key={index}
                {...value}
                {...props}
            />
        </div>
    )}
</div>
```

2017-09-18 12:36 UTC, sergeyisakov approved these changes

2017-09-18 12:36 UTC, merged